services:
  database:
    container_name: lexical_test
    restart: unless-stopped
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - lexical_test:/var/lib/postgresql/data/
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - app_network

volumes:
  lexical_test:

networks:
  app_network:
    name: lexical_network
    driver: bridge
